### ISSUE TITLE
Customize options cannot be saved in Wordpress 4.7.3

### ISSUE THREAD

**Issue by ForbodingAngel** [Clorith/wordpress-simple-customizer#5]
If you make changes to customize settings and then click on "Save and Publish", the save and publish button cycles and returns to it's former state. When navigating away from the customizer you are informed that your changes have not been saved. Indeed, a refresh shows that they have, in fact, not been saved.

**Comment by Clorith** [comment]
Addressed in [version 1.6.6](https://downloads.wordpress.org/plugin/simple-customizer.1.6.6.zip)

**Comment by ForbodingAngel** [comment]
Thank you so much! :-)
